-- begin DEMO_CUSTOMER
alter table DEMO_CUSTOMER add constraint FK_DEMO_CUSTOMER_DETAILS foreign key (DETAILS_ID) references DEMO_CUSTOMER_DETAILS(ID)^
-- end DEMO_CUSTOMER
-- begin DEMO_PHONE
alter table DEMO_PHONE add constraint FK_DEMO_PHONE_CUSTOMER_DETAILS foreign key (CUSTOMER_DETAILS_ID) references DEMO_CUSTOMER_DETAILS(ID)^
create index IDX_DEMO_PHONE_CUSTOMER_DETAILS on DEMO_PHONE (CUSTOMER_DETAILS_ID)^
-- end DEMO_PHONE
