alter table DEMO_PHONE add constraint FK_DEMO_PHONE_CUSTOMER_DETAILS foreign key (CUSTOMER_DETAILS_ID) references DEMO_CUSTOMER_DETAILS(ID);
create index IDX_DEMO_PHONE_CUSTOMER_DETAILS on DEMO_PHONE (CUSTOMER_DETAILS_ID);
